config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :documents, except: :destroy do
    member do
      get :versions
      patch :lock
      patch :unlock
    end
  end

  get "/your_documents", to: "documents#your_documents", as: 'your_documents'

  delete 'documents/:id/destroy', to: 'documents#destroy', as: 'destroy_document'

  get "/about", to: "pages#about", as: 'about'

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
require 'rest-client'

class Document < ApplicationRecord
  belongs_to :user
  has_many_attached :files
  has_paper_trail
  has_one_attached :preview_image






end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  # Store the URL the user was trying to access
  def store_user_location!
    # Store the location in the session only if it's a GET request and not an AJAX request
    # and the current path isn't related to Devise's login/signup
    if request.get? && !request.xhr? && !devise_controller? && !request.path.include?('login') && !request.path.include?('sign_up')
      session[:return_to] = request.fullpath
    end
  end

  # Determine if we should store the user's location
  def storable_location?
    !devise_controller? && !request.xhr? && !request.path.include?('login') && !request.path.include?('sign_up')
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!, only: [:update, :new]

  def index
    @documents = Document.all
    if params[:query].present?
      session[:search_query] = params[:query]
      query = "%#{params[:query].downcase}%"
      @documents = @documents.where("LOWER(title) LIKE ? or LOWER(description) LIKE ?", query, query)
    else
      session.delete(:search_query)
    end
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    @document.user = current_user
    @document.save!
    redirect_to root_path
  end

  def show
    @document = Document.find(params[:id])
    @user = @document.user
    @versions = @document.versions
    session[:return_to] = params[:return_to] if params[:return_to].present?
  rescue ActiveRecord::RecordNotFound
    redirect_to documents_path, alert: 'Document not found.'
  end

  def edit
    @document = Document.find(params[:id])
    session[:return_to] = request.referer
  end

  def update
    @document = Document.find(params[:id])
    PaperTrail.request.whodunnit = current_user.id if current_user
    @document.update(document_params)
    return_to = session.delete(:return_to)
    search_query = session[:search_query]
    if return_to&.include?(your_documents_path) && search_query.present?
      redirect_to your_documents_path(query: session[:search_query]), notice: 'Document was successfully updated.'
    elsif !return_to&.include?(your_documents_path) && search_query.present?
      redirect_to documents_path(query: session[:search_query]), notice: 'Document was successfully updated.'
    elsif return_to&.include?(your_documents_path) && search_query.blank?
      redirect_to your_documents_path, notice: 'Document was succesfully updated.'
    else
      redirect_to documents_path, notice: 'Document was succesfully updated.'
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to your_documents_path
  end

  def your_documents
    @documents = Document.where(user: current_user)
    if params[:query].present?
      session[:search_query] = params[:query]
      query = "%#{params[:query].downcase}%"
      @documents = @documents.where("LOWER(title) LIKE ? or LOWER(description) LIKE ?", query, query)
    else
      session.delete(:search_query)
    end
  end

  def versions
    @document = Document.find(params[:id])
    @versions = @document.versions
  end

  def lock
    @document = Document.find(params[:id])
    PaperTrail.request.whodunnit = current_user.id if current_user
    @document.update(locked: true)

    respond_to do |format|
      format.json { render json: { success: true } }
      format.html { redirect_to documents_path, notice: 'Document locked.' }
    end
  end

  def unlock
    @document = Document.find(params[:id])
    PaperTrail.request.whodunnit = current_user.id if current_user
    @document.update(locked: false)

    respond_to do |format|
      format.json { render json: { success: true } }
      format.html { redirect_to documents_path, notice: 'Document unlocked.' }
    end

  end

  private

  def document_params
    params.require(:document).permit(:image, :title, :description, :transcription, :user_id, files: [])
  end

  def authenticate_user!
    unless user_signed_in?
      store_location_for(:user, request.fullpath) # Store the full path for redirect after login
      redirect_to new_user_session_path, alert: 'Please log in to continue.'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_card.html.erb
  <div class="pic">
    <% if document.files.attached? %>
      <canvas class="preview" id="pdf-canvas-<%= document.id %>"></canvas>
      <img class="preview" id="jpeg-image-<%= document.id %>"/>
    <% end %>
  </div>
  <div class="info">
    <div class="card-head">
      <div class="title">
        <h2><%= document.title %></h2>
      </div>
      <% if controller_name == 'documents' && action_name == 'your_documents' %>
        <div class="popout">
          <button id="gear-button"><i class="bi bi-gear-fill"></i></button>
          <ul class="hidden popout-menu">
            <li class="lock" data-document-id="<%= document.id %>">Prohibit other users from transcribing <span class="tick-icon <%= document.locked == true ? 'visible' : '' %>"><i class="bi bi-check2"></i></span></li>
            <li class="unlock" data-document-id="<%= document.id %>">Allow other user to transcribe <span class="tick-icon <%= document.locked == false ? 'visible' : '' %>"><i class="bi bi-check2"></i></span></li>
            <li class="edit-link" data-href="<%= edit_document_path(document) %>">Edit</li>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="description">
    <p><%= document.description %></p>
    </div>
  </div>


<script>
  document.addEventListener("turbo:load", function() {
    const fileUrl = '<%= url_for(document.files.first) %>';
    const canvas = document.getElementById('pdf-canvas-<%= document.id %>');
    const img = document.getElementById('jpeg-image-<%= document.id %>');
    const fileExtension = fileUrl.split('.').pop().toLowerCase();
    if (fileExtension === 'pdf') {
      const loadingTask = pdfjsLib.getDocument(fileUrl);
      loadingTask.promise.then(pdf => {
        pdf.getPage(1).then(page => {
          const scale = 1.5;
          const viewport = page.getViewport({ scale: scale });
          const context = canvas.getContext('2d');
          canvas.height = viewport.height;
          canvas.width = viewport.width;

          const renderContext = {
            canvasContext: context,
            viewport: viewport
          };
          page.render(renderContext);
        });
      }).catch(error => {
        console.error('Error loading PDF:', error);
      });
    } else {
      img.src = fileUrl;
      img.style.display = 'block'; // Show image
      canvas.style.display = 'none'; // Hide canvas
    }

     // Add popout menu toggle for all gear buttons
    document.querySelectorAll('.popout button').forEach(gearButton => {
      // Use a unique listener function to avoid duplication
      const toggleMenu = function(event) {
        event.stopPropagation(); // Prevent click from bubbling up
        event.preventDefault();

        // Find the closest popout menu to the clicked button
        const popoutMenu = this.nextElementSibling; // Assuming the popout menu is immediately after the button
        if (popoutMenu) {
          const isHidden = popoutMenu.classList.contains('hidden');
          // Close all menus first
          document.querySelectorAll('.popout-menu').forEach(menu => menu.classList.add('hidden'));
          // Toggle the clicked menu
          if (isHidden) {
            popoutMenu.classList.remove('hidden');
          }
          console.log('Menu hidden:', popoutMenu.classList.contains('hidden')); // Debug log
        }
      };

      // Add the event listener only if it hasn't been added before
      if (!gearButton.dataset.listenerAdded) {
        gearButton.addEventListener('click', toggleMenu);
        gearButton.dataset.listenerAdded = true; // Mark listener as added
      }
    });

    // Close menu if clicking outside
    document.addEventListener('click', function() {
      const popoutMenus = document.querySelectorAll('.popout-menu');
      popoutMenus.forEach(menu => {
        if (!menu.classList.contains('hidden')) {
          menu.classList.add('hidden');
          console.log('Menu closed');
        }
      });
    });

    // Handle the click event for the lock menu item
    document.querySelectorAll('.popout-menu li.lock').forEach(item => {
      item.addEventListener('click', function(event) {
        const documentId = this.getAttribute('data-document-id');
        event.stopPropagation();
        event.preventDefault();

        fetch(`/documents/${documentId}/lock`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content // Ensure CSRF token is included
          }
        })
        .then(response => {
          if (response.ok) {
            console.log('Document locked successfully');
            item.querySelector('.tick-icon').classList.add('visible')
            this.nextElementSibling.querySelector('.tick-icon').classList.remove('visible');
          } else {
            console.error('Failed to lock the document');
          }
        })
        .catch(error => console.error('Error:', error));
      });
    });

    //Click event for unlock meu item
    document.querySelectorAll('.popout-menu li.unlock').forEach(item => {
      item.addEventListener('click', function(event) {
        const documentId = this.getAttribute('data-document-id');
        event.stopPropagation();
        event.preventDefault();

        fetch(`/documents/${documentId}/unlock`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content // Ensure CSRF token is included
          }
        })
        .then(response => {
          if (response.ok) {
             console.log('Document unlocked successfully');
             item.querySelector('.tick-icon').classList.add('visible');
             this.previousElementSibling.querySelector('.tick-icon').classList.remove('visible');
          } else {
            console.error('Failed to unlock the document');
          }
        })
        .catch(error => console.error('Error:', error));
      });
    });

    // Prevent event propagation for the edit link
    document.querySelectorAll('.popout-menu .edit-link').forEach(link => {
      link.addEventListener('click', function(event) {
        event.stopPropagation();
        const url = this.getAttribute('data-href');
        window.location.href = url;
      });
    });
  });
</script>

app/views/documents/edit.html.erb
<div class="content">
<div class="position-relative">
  <h1 class="text-center">Edit Your Document</h1>
   <%= form_with url: destroy_document_path(@document), method: :delete, class: "delete-form" do |f| %>
      <%= f.hidden_field :document_id, value: @document.id %> <!-- Hidden field for document ID -->
      <button type="submit" class="btn btn-secondary position-absolute bg-transparent border-0 top-0 end-0 p-2 me-4 fs-4" id="delete-document-btn">
        <i class="bi bi-trash"></i>
      </button>
    <% end %>
</div>
  <div class="add-doc">
    <%= simple_form_for [@document] do |f| %>
      <div class="form">
        <%= f.input :title,
                    required: true,
                    autofocus: true %>
        <%= f.input :description, as: :text, :input_html => { :cols => 5, :rows => 3 },
                    required: true,
                    autofocus: true %>

        <div class="text-center">
          <%= f.button :submit, "Save Document", class: 'btn-secondary' %>
        </div>
        <br>
      </div>
    <% end %>
  </div>
</div>

<script>
  document.getElementById("delete-document-btn").addEventListener("click", function(event) {
    // Ask for confirmation before submitting the form
    if (!confirm("Are you sure you want to delete this document?")) {
      event.preventDefault();  // Prevent form submission if canceled
    }
  });
</script>

app/views/documents/index.html.erb
<div class="head-index d-flex align-items-center justify-content-center">
  <h1 class>Documents</h1>
</div>
<div class="results">
  <div class="d-flex justify-content-center">
    <div class="col-7">
        <%= form_with url: documents_path, method: :get, class: "d-flex search-index" do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control search-bar-index",
              placeholder: "Search Documents"
          %>
          <%= submit_tag "Search", name: "", class: "button" %>
        <% end %>
          <br>
          <div class="property-counter">
            <% if @documents.present? %>
              <p><%= @documents.size %> search results</p>
            <% else %>
              <p>No documents found</p>
            <% end %>
          </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="doc-list col-8">
      <% if @documents.any? %>
        <% @documents.each do |document| %>
          <div class="doc" data-url="<%= document_path(document, return_to: request.fullpath) %>">
            <%= render "card", document: document %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.querySelectorAll('.doc').forEach(doc => {
    doc.addEventListener('click', function() {
      const url = this.getAttribute('data-url');
      window.location.href = url;
    });
  });

</script>

app/views/documents/new.html.erb
<div class="content">
  <h1>Add Your Document</h1>
  <div class="add-doc">
    <%= simple_form_for [@document] do |f| %>
      <div class="form">
        <%= f.input :title,
                    required: true,
                    autofocus: true %>
        <%= f.input :description, as: :text, :input_html => { :cols => 5, :rows => 3 },
                    required: true,
                    autofocus: true %>
        <%= f.input :transcription, as: :text, :input_html => { :cols => 5, :rows => 10 },
                    autofocus: true %>
        <%= f.input :files, as: :file, input_html: { multiple: true }, required: true %>
        <div class="file-upload-info">
          <p><strong>Accepted file types:</strong> PDF and JPEG. You can upload multiple files at once. Files will be displayed in the order that they are uploaded.</p>
        </div>
        <div class="text-center">
          <%= f.button :submit, "Add Document", class: 'btn-secondary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/show.html.erb
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script type='text/javascript'>

        // Refresh page automatically one time upon loading
        (() => {
            if (window.localStorage) {

                // If there is no item as 'reload'
                // in localstorage then create one &
                // reload the page
                if (!localStorage.getItem('reload')) {
                    localStorage['reload'] = true;
                    window.location.reload();
                } else {

                    // If there exists a 'reload' item
                    // then clear the 'reload' item in
                    // local storage
                    localStorage.removeItem('reload');
                }
            }
        })(); // Calling anonymous function here only
    </script>
</head>

<div class="head">
  <% if @document %>

    <h1><%= @document.title %></h1>

    <p class="fs-6 description"><%= @document.description %></p>

  <% else %>
    <p>Document not found</p>
  <% end %>
</div>
<%= puts user_signed_in? %>
<div class="show">
  <div class='transcription'>
    <% if user_signed_in? && (@document.locked == false || (@document.locked == true && current_user.id == @document.user_id)) %>

      <%= simple_form_for [@document], url: document_path(@document), method: :put do |f| %>
        <div class="box">
          <%= f.input :transcription, as: :text, :input_html => { :cols => 70, :rows => 20 } %>
        </div>
        <div class="text-center">
              <%= f.button :submit, "Save", class: 'btn-primary' %>
        </div>
      <% end %>
    <% elsif @document.locked == false && user_signed_in? == false %>
      <%= simple_form_for [@document], url: document_path(@document), method: :put do |f| %>
        <div class="box">
          <%= f.input :transcription, as: :text, :input_html => { :cols => 70, :rows => 20 } %>
        </div>
        <div class="text-center">
              <%= f.button :submit, "Login to Edit", class: 'btn-primary' %>
        </div>
      <% end %>
    <% else %>
      <p>Transcription</p>
      <textarea class="p-3" rows="18" cols="70" readonly><%= @document.transcription %></textarea>
      <br>
      <br>
      <div class="text-center">
        <div class="badge bg-primary text-wrap text-center">
          <h5>Document owner has locked transcriptions</h5>
        </div>
      </div>
    <% end %>
    <br>
    <br>
    <% if @versions.present? && @versions.last.whodunnit.present? %>
      <p><%= link_to "Last updated by #{User.find(@versions.last.whodunnit).username} at #{@versions.last.created_at}", versions_document_path(@document)%></p>
    <% end %>
  </div>

  <div class="container-outer">
    <div class="d-flex justify-content-between max-w-100">
      <div>
        <% if @document.files.size > 1 %>
          <button id="prev-file" class="btn-arrow">←</button>
          <button id="next-file" class="btn-arrow">→</button>
        <% end %>
      </div>
      <% if @document.files.size > 1 %>
        <p>Page <span id="pageNumber">1</span> / <%= @document.files.size %></p>
      <% end %>
      <p class="text-end mb-1">Hold control key to zoom</p>
    </div>
    <div id="pdf-container"></div>
  </div>
  <script>
    function initPDF() {
        let currentFileIndex = 0; // Start with the first file
        const files = <%= raw(@document.files.map { |f| url_for(f) }.to_json) %>; // Array of file URLs
        const pdfjsLib = window['pdfjs-dist/build/pdf'];
        pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.worker.min.js';

        let pdfDoc = null;
        let scale = 1.0; // Start with a default zoom level
        let img;

        // Function to load PDF file
        function loadPDF() {
          const url = files[currentFileIndex]; // Get the current file URL
          const container = document.getElementById('pdf-container');
          container.innerHTML = ''; // Clear the container before rendering
          container.scrollTop = 0
          scale = 1.0;
          const isPDF = url.endsWith('.pdf');
          if (isPDF) {
            const container = document.getElementById('pdf-container');
            const loadingTask = pdfjsLib.getDocument(url);
            loadingTask.promise.then(pdf => {
              pdfDoc = pdf;
              renderAllPages(); // Render all pages initially
            }).catch(error => {
              console.error('Error loading PDF: ', error);
            });
          } else {
            loadImage(url); // Load image if it's not a PDF
          }
        }

        // Function to render all pages of the PDF
        function renderAllPages() {
          const container = document.getElementById('pdf-container');
          container.innerHTML = ''; // Clear the container before rendering

          for (let pageNum = 1; pageNum <= pdfDoc.numPages; pageNum++) {
            pdfDoc.getPage(pageNum).then(page => {
              const viewport = page.getViewport({ scale });
              const canvas = document.createElement('canvas');
              const context = canvas.getContext('2d');
              canvas.height = viewport.height;
              canvas.width = viewport.width;

              const renderContext = {
                canvasContext: context,
                viewport: viewport
              };
              page.render(renderContext);

              // Append the canvas to the container
              container.appendChild(canvas);
            });
          }
        }

        // Function to load image files
        function loadImage(url) {
          const container = document.getElementById('pdf-container');
          img = document.createElement('img');
          img.src = url;
          img.style.maxWidth = '100%'; // Scale the image to fit the container
          img.style.transition = `transform 0.2s`; // Smooth scaling transition
          img.style.transform = `scale(${scale})`; // Apply initial scale
          container.appendChild(img);

          img.onerror = () => {
            console.error('Error loading image: ', url);
          };

          img.onload = () => {
            // Adjust the container size if needed
            container.style.width = `${img.width}px`;
            container.style.height = `${img.height}px`;
          };
        }

        // Function to show the next file
        function showNextFile() {
          if (currentFileIndex < files.length - 1) {
            currentFileIndex++;
            document.getElementById('pageNumber').textContent = currentFileIndex + 1
            loadPDF(); // Reload the new file
          }
        }

        // Function to show the previous file
        function showPrevFile() {
          if (currentFileIndex > 0) {
            currentFileIndex--;
            document.getElementById('pageNumber').textContent = currentFileIndex + 1
            loadPDF(); // Reload the previous file
          }
        }

        // Event listeners for navigation buttons
        if (files.length > 1) {
        document.getElementById('next-file').addEventListener('click', showNextFile);
        document.getElementById('prev-file').addEventListener('click', showPrevFile);
        }

        // Mouse wheel zooming with Ctrl key
        const container = document.getElementById('pdf-container');
        container.addEventListener('wheel', (event) => {
            if (event.ctrlKey) {
                event.preventDefault(); // Prevent the default scroll behavior

                const mouseX = event.clientX - container.getBoundingClientRect().left;
                const mouseY = event.clientY - container.getBoundingClientRect().top;

                const previousScale = scale;

                if (event.deltaY < 0) {
                    scale += 0.1; // Zoom in
                } else {
                    scale = Math.max(scale - 0.1, 0.2); // Zoom out
                }

                const newScale = scale / previousScale;

                if (pdfDoc) {
                    container.scrollLeft += (mouseX * newScale) - mouseX;
                    container.scrollTop += (mouseY * newScale) - mouseY;
                  renderAllPages(); // Re-render pages with new scale
                } else if (img) {
                    img.style.transform = `scale(${scale})`; // Update the scale of the image
                    img.style.transformOrigin = `${mouseX}px ${mouseY}px`; // Set zoom origin to mouse position
                }
            }
        });

        // Click and Drag Functionality
      let isDragging = false;
      let startX, startY, scrollLeft, scrollTop

      container.addEventListener('mousedown', (e) => {
          e.preventDefault();

          isDragging = true;
          container.classList.remove('grab');
          container.classList.add('grabbing');
          startX = e.pageX;
          startY = e.pageY;
          scrollLeft = container.scrollLeft;
          scrollTop = container.scrollTop;
      });

      container.addEventListener('mouseleave', () => {
          isDragging = false;
          container.classList.remove('grabbing');
          container.classList.add('grab');
      });

      container.addEventListener('mouseup', () => {
          isDragging = false;
          container.classList.remove('grabbing')
          container.classList.add('grab')
      });

      container.addEventListener('mousemove', (e) => {
          if (!isDragging) return;

          e.preventDefault();
          const x = e.pageX;
          const y = e.pageY;

          const walkX = (x - startX);
          const walkY = (y - startY);

          container.scrollLeft = scrollLeft - walkX;
          container.scrollTop = scrollTop - walkY;
      });

      container.classList.add('grab')
        // Load the PDF initially
        loadPDF();
    }

    document.addEventListener('turbo:load', initPDF);

  </script>

</div>

app/views/documents/versions.html.erb
<div class="head-v">
  <h1> <%= @document.title %> - Edit History</h1>
</div>
<div class="edit-history d-flex">
  <div class='versions'>
    <% @versions.reverse.each_with_index do |version, index| %>
      <% user = User.find_by(id: version.whodunnit) %>
      <% if user %>
        <% document_data = YAML.safe_load(version.object, permitted_classes: [ActiveSupport::TimeWithZone, ActiveSupport::TimeZone, Time], aliases: true) %>
        <div class="version-card" data-transcription="<%= document_data['transcription'] %>" data-index="<%= index %>" current-transcription="<%= @document.transcription %>">
          <p><%= version.created_at %> updated by <%= user.username %></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="transcription-container">
    <textarea id="transcription-text" rows="17" cols="70" readonly></textarea>
  </div>
</div>

<script>
  const versions = document.querySelectorAll('.version-card')
  versions.forEach((version) => {
    version.addEventListener("click", (event) => {
      const index = parseInt(version.getAttribute('data-index'));
      console.log(index)
      if (index > 0) {
        const nextVersion = versions[index - 1];
        const transcription = nextVersion.getAttribute('data-transcription');
        document.getElementById('transcription-text').value = transcription;
      } else {
        document.getElementById('transcription-text').value = version.getAttribute('current-transcription');
      };
      versions.forEach(v => v.classList.remove('selected'))
      version.classList.add('selected')
    });
  })



</script>

app/views/documents/your_documents.html.erb
<div class="head-index d-flex align-items-center justify-content-center">
  <h1 class>Your Documents</h1>
</div>
<div class="results">
  <div class="d-flex justify-content-center">
    <div class="col-7">
        <%= form_with url: your_documents_path, method: :get, class: "d-flex search-index" do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control search-bar-index",
              placeholder: "Search Documents"
          %>
          <%= submit_tag "Search", name: "", class: "button" %>
        <% end %>
          <br>
          <div class="property-counter">
            <% if @documents.present? %>
              <p><%= @documents.size %> search results</p>
            <% else %>
              <p>No documents found</p>
            <% end %>
          </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="doc-list col-8">
      <% if @documents.any? %>
        <% @documents.each do |document| %>
          <div class="doc" data-url="<%= document_path(document, return_to: request.fullpath) %>">
            <%= render "card", document: document %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.querySelectorAll('.doc').forEach(doc => {
    doc.addEventListener('click', function() {
      const url = this.getAttribute('data-url');
      window.location.href = url;
    });
  });

</script>

app/views/pages/home.html.erb
<header>
  <h1>TranscribeHistory</h1>
  <div class="nav">
    <li><button class="home"><%= link_to "About", about_path %></button></li>
    <li><button class="home"><%= link_to "Add a Document", new_document_path %></button></li>
    <% if user_signed_in? %>
      <li><button class="home"><%= link_to "Your Documents", your_documents_path %></button></li>
    <% end %>
    <li><% if user_signed_in? %>
      <button class="home"><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %></button>
    <% else %>
      <button class="home"><%= link_to "Login", new_user_session_path %></button>
    <% end %></li>
  </div>
</header>
<div class="main d-flex justify-content-center">
  <div class="col-7 search-container">
    <%= form_with url: documents_path, method: :get, class: "d-flex search" do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control search-bar",
          placeholder: "Search Documents"
      %>
      <%= submit_tag "Search", name: "", class: "button" %>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>